# ConfigMap: lưu config KHÔNG nhạy cảm (URL, host, port...)
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demodb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATA_REDIS_HOST: redis
